version: "3.9"

services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/reminder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
