# Generated by Django 3.1.7 on 2021-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Статус напоминания'),
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='reminder_time',
            field=models.DateTimeField(blank=True, verbose_name='Время напоминания'),
        ),
    ]
